<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="wheel_width" value="0.132" />
  <xacro:property name="front_axis_X" value="2.2" />
  <xacro:property name="wheel_base_rear" value="0.35" />
  <xacro:property name="wheel_base_front" value="0.225" />
  
  <xacro:property name="wheel_radius" value="0.3" />
  <xacro:property name="manip_x" value="0.6" />
  <xacro:property name="manip_y" value="0.2" />
  <xacro:property name="manip_z" value="0.0" />
  
    <link name="base_link">
      <inertial>
        <origin rpy="0.000000 -0.000000 -1.570796" xyz="1.003638 0.000000 0.000000"/>
        <!-- TODO: Update mass as volume from Meshlab will overestimate the mass -->
        <mass value="300"/>
        <inertia ixx="50.0" ixy="0.0" ixz="0.0" iyy="240.0" iyz="0.0" izz="250.0"/>
      </inertial>
      <visual>
        <origin rpy="0.000000 -0.000000 -1.570796" xyz="1.101831 0.000000 0.000000"/>
        <geometry>
          <mesh filename="meshes/VehicleBody/VehicleBody.dae" scale="1 1 1"/>
        </geometry>
      </visual> 
      <collision>
        <origin rpy="1.570796 -0.000000 1.570796" xyz="0.002268 -0.000000 0.668965"/>
        <geometry>
           <box size="0.592215 0.491737 0.491032"/>
         </geometry>
       </collision>
       <collision>
        <origin rpy="-1.570796 -0.000000 -3.141593" xyz="0.963687 -0.000000 0.804149"/>
        <geometry>
           <box size="1.427517 0.762107 0.592215"/>
         </geometry>
       </collision>
       <collision>
        <origin rpy="0.000000 -0.000000 0.000000" xyz="2.197615 0.000000 0.762109"/>
        <geometry>
           <box size="0.583352 0.544691 0.264003"/>
         </geometry>
       </collision>
       <collision>
        <origin rpy="-1.570796 -0.000000 -3.141593" xyz="2.083368 0.000000 0.526601"/>
        <geometry>
           <box size="0.811846 0.207011 0.097965"/>
         </geometry>
       </collision>
       <collision>
        <origin rpy="1.570796 -0.000000 1.570796" xyz="-0.288170 -0.000000 0.522611"/>
        <geometry>
           <box size="0.592215 0.236236 0.089846"/>
         </geometry>
       </collision>
       <collision>
        <origin rpy="1.570796 -0.000000 1.570796" xyz="2.5402429 0.000000 0.562592"/>
        <geometry>
           <box size="0.437199 0.131902 0.055878"/>
         </geometry>
       </collision>
       <collision>
        <origin rpy="1.570796 -0.000000 1.570796" xyz="1.791692 -0.000000 0.907655"/>
        <geometry>
           <box size="0.592215 0.555096 0.228493"/>
         </geometry>
       </collision>         

    </link>

    <link name="wheel_rear_right_link">
      <inertial>
        <origin rpy="0 0 0" xyz="0 0.0 0.0"/>
        <mass value="24.5"/>
        <inertia ixx="0.787" ixy="0.0" ixz="0.0" iyy="0.787" iyz="0.0" izz="1.309"/>
      </inertial>

      <visual>
        <origin rpy="0 1.571 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="meshes/Wheels/WheelRight.dae" scale="1 1 1"/>
        </geometry>
      </visual>

      <collision>
        <origin rpy="0 0 0" xyz="0 0 ${-wheel_width/2}"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
      </collision>
    </link>

    <link name="wheel_rear_left_link">
      <inertial>
        <origin rpy="0 0 0" xyz="0 0.0 ${wheel_width}"/>
        <mass value="24.5"/>
        <inertia ixx="0.787" ixy="0.0" ixz="0.0" iyy="0.787" iyz="0.0" izz="1.309"/>
      </inertial>

      <visual>
        <origin rpy="0 1.571 0 " xyz="0 0 0.0"/>
        <geometry>
          <mesh filename="meshes/Wheels/WheelLeft.dae" scale="1 1 1"/>
        </geometry>
      </visual>

      <collision>
        <origin rpy="0 0 0" xyz="0 0 ${wheel_width/2}"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
      </collision>
    </link>

    <link name="wheel_front_right_link">
      <inertial>
        <origin rpy="0 0 0" xyz="0 0.0 ${wheel_width/2}"/>
        <mass value="24.5"/>
        <inertia ixx="0.787" ixy="0.0" ixz="0.0" iyy="0.787" iyz="0.0" izz="1.309"/>
      </inertial>

      <visual>
        <origin rpy="0 1.571 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="meshes/Wheels/WheelRight.dae" scale="1 1 1"/>
        </geometry>
      </visual>

      <collision>
        <origin rpy="0 0 0" xyz="0 0 ${-wheel_width/2}"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
      </collision>
    </link>

    <link name="wheel_front_left_link">
      <inertial>
        <origin rpy="0 0 0" xyz="0 0.0 ${wheel_width/2}"/>
        <mass value="24.5"/>
        <inertia ixx="0.787" ixy="0.0" ixz="0.0" iyy="0.787" iyz="0.0" izz="1.309"/>
      </inertial>

      <visual>
        <origin rpy="0 1.571 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="meshes/Wheels/WheelLeft.dae" scale="1 1 1"/>
        </geometry>
      </visual>

      <collision>
        <origin rpy="0 0 0" xyz="0 0 ${wheel_width/2}"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
      </collision>
    </link>

  


    <link name="steering_front_right_link">
      <inertial>
        <origin rpy="0 0 -1.571" xyz="0 0 -0.04"/>
        <mass value="20.0"/>
        <inertia ixx="1" ixy="0.0" ixz="0.0" iyy="1" iyz="0.0" izz="1"/>
      </inertial>

      <visual>
        <origin rpy="0 0 -1.571" xyz="0 -0.03 -0.03"/>
        <geometry>
          <mesh filename="meshes/Steering/SteeringArmRight.dae" scale="0.6 0.6 0.6"/>
        </geometry>
      </visual>
    </link>

    <link name="steering_front_left_link">
      <inertial>
        <origin rpy="0 0 -1.571" xyz="0 0 -0.04"/>
        <mass value="20.0"/>
        <inertia ixx="1" ixy="0.0" ixz="0.0" iyy="1" iyz="0.0" izz="1"/>
      </inertial>
      <visual>
        <origin rpy="0 0 -1.571" xyz="0 0.03 -0.03"/>
        <geometry>
          <mesh filename="meshes/Steering/SteeringArmLeft.dae" scale="0.6 0.6 0.6"/>
        </geometry>
      </visual>
    </link>


    <link name="lidar_mount">
      <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="1.0"/>
        <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
      </inertial>
    </link>


    <link name="conveyor_belt">
      <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="5.0"/>
        <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.5" iyz="0.0" izz="0.5"/>
      </inertial>
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="meshes/ConveyorBelt/ConveyorBelt.dae" scale="1.0 1.0 1.0"/>
        </geometry>
      </visual>
    </link>


    <joint name="wheel_rear_right_joint" type="continuous">
      <origin rpy="-1.570796 0.000000 0.000000" xyz="0.000000 ${-wheel_base_rear} ${wheel_radius}"/>
      <parent link="base_link"/>
      <child link="wheel_rear_right_link"/>
      <axis xyz="0.0 0.0 1.0"/>
      <limit effort="1000000.0" velocity="1000.0"/>
    </joint>

    <joint name="wheel_rear_left_joint" type="continuous">
      <origin rpy="-1.570796 -0.000000 0.000000" xyz="0.000000 ${wheel_base_rear} ${wheel_radius}"/>
      <parent link="base_link"/>
      <child link="wheel_rear_left_link"/>
      <axis xyz="0.0 0.0 1.0"/>
      <limit effort="1000000.0" velocity="1000.0"/>
    </joint>

    <joint name="wheel_front_right_joint" type="continuous">
      <origin rpy="-1.571 0 0" xyz="0 ${wheel_base_front-wheel_base_rear} 0"/>
      <parent link="steering_front_right_link"/>
      <child link="wheel_front_right_link"/>
      <axis xyz="0.0 0.0 1.0"/>
      <limit effort="1000000.0" velocity="1000.0"/>
    </joint>

    <joint name="wheel_front_left_joint" type="continuous">
      <origin rpy="-1.571 0 0" xyz="0 ${-wheel_base_front+wheel_base_rear} 0"/>
      <parent link="steering_front_left_link"/>
      <child link="wheel_front_left_link"/>
      <axis xyz="0.0 0.0 1.0"/>
      <limit effort="1000000.0" velocity="1000.0"/>
    </joint>

    <joint name="steering_front_right_joint" type="revolute">
      <origin rpy="0 0 0" xyz="${front_axis_X} ${-wheel_base_front} ${wheel_radius}"/>
      <parent link="base_link"/>
      <child link="steering_front_right_link"/>
      <axis xyz="0.0 0.0 1.0"/>
      <dynamics damping="2.0" friction="1.0"/>
      <limit effort="1000000.0" lower="-0.5235" upper="0.5235" velocity="100"/>
    </joint>

    <joint name="steering_front_left_joint" type="revolute">
      <origin rpy="0 0 0" xyz="${front_axis_X} ${wheel_base_front} ${wheel_radius}"/>
      <parent link="base_link"/>
      <child link="steering_front_left_link"/>
      <axis xyz="0.0 0.0 1.0"/>
      <dynamics damping="2.0" friction="1.0"/>
      <limit effort="1000000.0" lower="-0.5235" upper="0.5235" velocity="100"/>
    </joint>

    <joint name="lidar_mount_joint" type="fixed">
      <origin rpy="0 0 0" xyz="2.2804451 0.0 0.8967377"/>
      <parent link="base_link"/>
      <child link="lidar_mount"/>
    </joint>


    <joint name="conveyor_belt_joint" type="fixed">
      <origin rpy="0 0 1.571" xyz="1.1043353 0 0.0"/>
      <parent link="base_link"/>
      <child link="conveyor_belt"/>
    </joint>
 
</robot>
